<?php

namespace Home\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-07 at 18:41:43.
 */
class SubscribeControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SubscribeController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SubscribeController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Home\Controller\SubscribeController::mySubscribe
     * @todo   Implement testMySubscribe().
     */
    public function testMySubscribe() {
        
        
    }
    
    public function testMySubscribe_EmptyInput_ReturnString(){
        
    }

    /**
     * @covers Home\Controller\SubscribeController::addKeyword
     * @todo   Implement testAddKeyword().
     */
    public function testAddKeyword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Home\Controller\SubscribeController::remove
     * @todo   Implement testRemove().
     */
    public function testRemove() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Home\Controller\SubscribeController::history
     * @todo   Implement testHistory().
     */
    public function testHistory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
